spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss}){faint} %clr(%-5level){green} %clr(%logger{18}){cyan} : %msg%n"

  level:
    org.hibernate: ERROR
    org.springframework.security: ERROR
    org.springframework.web: WARN
    org.springframework.messaging: WARN
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.orm.jpa: ERROR

management:
  endpoint:
    web:
      exposure:
        include: health
    health:
      show-details: always